feat(core): 添加转小写 解析命令 小写处理
liyupi/yuindex pull request #62
Opened 2022-07-31 06:43 UTC by Jeffrey-mu

[命令解析 兼容大写](https://github.com/liyupi/yuindex/issues/60)

2022-07-31 06:51 UTC, Jeffrey-mu commented
- 严格意义上来说命令不区分大小写
- 只对命令做小写处理 参数不做处理
- 这是个好的PR🌟🌟🌟

2022-08-05 14:32 UTC, liyupi requested changes
too simple

2022-08-05 14:32 UTC, liyupi commented on src/core/commandExecutor.ts
> +};
这个感觉没必要单独封装一个函数，而且不建议把这种公用的函数放到职责无关的文件中

2022-08-11 13:49 UTC, closed without merging

2022-08-11 13:49 UTC, Jeffrey-mu commented
close